language: go
script: go build -v
after_script: ls -al
addons:
  apt:
    packages:
    - xorg-dev
    - libegl1-mesa-dev
    - libgl1-mesa-dev
    update: true
deploy:
  provider: releases
  api_key: 
    secure: "CExsSsA59baDDfUkT45o56GVnCR4b35dVkb++2MiVi/XLMc2y6jjWmWdBj1Bxt7Tm3Z4O+NEigmcFe9As7c/Sx6YtR8TpUKXplSP0voLf60XHb1VF0EEyTs/NBfCPSTRBQc3V8pqCrIJK1BIX0KxUcRaL3xNcpG+6HnwNHoZE3Iwb/mgoWekWbiGwd3vshFcTck4TbTFuTgNwS/+EZvG9v+Jz4vTfT3oY7Ty1vLkHOKQfofe/m9ZNlKrektrz5zIDIDoarLrmLqrHhvvZU7d2XjOuy/d3oRin5V3s6xm5+v8s2u0T7WwLcm2miuzakfk8KlODdn9s7rrT+m6ij3BmaFPQwSOFS3T7D5ORBxPPA9nKTzPtRn6ud8vlvaEs/UwOoLzl3ml92qghF4eXJtrvnzzxIxLp/3ZLgZ9NP3MRpI/MNr89Zcv6qIiDn1bt7PC+Qs4WeGiH0bU+073mVoYbUB086CC3P+9F1Pz2eI+3H796bR+aWD4gi8be27OxlDQvQatZ7j8B/Vqu6wxces5Y6VQ3RPQaWXemCaJiqJUghO8qUSlc/Lu3dfDunyR6tF0bEIV2ctfAS6lbhtLolb/gk+aYacgysZrNEMj9jjmAsLt/NWsaiTWW7Ey45R5vWksoeoUOxvb0WZl+m2ue+EyGO6edaYVua4L1dAooRtGExE="
  file: MRS-fyne-launcher
  skip_cleanup: true
  draft: true
